[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_swap = "7aEi72qNaX16AJBDhgsmsPvyXuMKCXea9qRA2jVL6Hjg"

[registry]
url = "https://api.testnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
